- name: condtions demo
  hosts: local
  connection: local
  vars:
  NUMBER: 77
  tasks:
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than or equal to 100
    when: number < 100 

    
