- name: variables from prompt 
  hosts: local
  connection: local
  vars_prompt:
- name: username
  prompt: please enter user name
  private: true

- name: password
  prompt: please enter password
  private: true
  tasks:
  - name: print user information
    ansible.builtin.debug:
      msg: "Hello user name is: {{ USERNAME }}, password is {{ PASSWORD }}"